# Generated by Django 3.0.6 on 2020-06-03 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posters_app', '0001_initial'),
        ('messages_app', '0002_remove_message_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contents',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posters_app.Poster'),
        ),
    ]
