# Generated by Django 3.0.6 on 2020-06-03 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_auto_20200602_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
