# Generated by Django 3.0.6 on 2020-06-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='contents',
            field=models.CharField(max_length=5000),
        ),
    ]
