# Generated by Django 3.0.6 on 2020-05-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posters_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soundbyte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('directory', models.CharField(max_length=255)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('caption', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('duration_sec', models.CharField(default='60', max_length=255)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posters_app.Poster')),
            ],
        ),
    ]
