# Generated by Django 3.0.6 on 2020-06-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundbytes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundbyte',
            name='duration_sec',
            field=models.IntegerField(default='7'),
        ),
    ]
